### ISSUE TITLE
Add Judgment of Paris Content to JOP Story page

### ISSUE THREAD

**Issue by wrenaria** [ucd-library/intertwine#32]
Judgment of Paris content needs added to the JOP story page.

Here's the image content and rough layout for content. You should be able to copy and paste the text from the PDF. Everything should follow the same layout rules as Chardonnay. 

https://drive.google.com/drive/u/1/folders/1f8OPNcNM-s9_ZeNAIAMyul8k847D-A46

**Comment by wrenaria** [comment]
One of the captions is being pulled into the section title instead of showing as an image caption. 

![Screen Shot 2020-09-17 at 10 43 40 AM](https://user-images.githubusercontent.com/17831969/93507517-ab5c6080-f8d2-11ea-970b-728df2d96f6c.png)

- "The Winning Wines" is a caption and should not be part of the title. 

- The triptych is also displayed in an incorrect order. Here is the correct order as shown on trello: https://trello.com/c/B5deTaip/104-triptych

**Comment by ldragoon** [comment]
Note to self: connected to issue https://github.com/ucd-library/intertwine/issues/51.

Ordering for Triptych items in trello2moment still not correct.

**Comment by qjhart** [comment]
The current representation of the triptych seems to include the proper order; with `make key=${key} token=${tok} moment=jop board=K2CNYMZP jop_moment.ttl` 

```ttl
<#B5deTaip> schema:name "Triptych";
    schema:publisher <http://id.loc.gov/authorities/names/no2008108707>;
    schema:license <http://rightsstatements.org/vocab/CNE/1.0/>;
    schema:position "9"^^<http://www.w3.org/2001/XMLSchema#integer>;
    a ucdlib:Story;
    schema:label "Story: Triptych";
    a schema:WebPage;
    schema:image [
  a schema:ImageObject;
  schema:position "1"^^<http://www.w3.org/2001/XMLSchema#integer>;
  schema:caption "Patricia Gallagher, Steven Spurrier, Odette Kahn";
  schema:contentUrl <B5deTaip/jop-tasting1.jpg>
], [
  a schema:ImageObject;
  schema:position "2"^^<http://www.w3.org/2001/XMLSchema#integer>;
  schema:caption "George Taber's Article";
  schema:contentUrl <B5deTaip/jop-article.jpg>
], [
  a schema:ImageObject;
  schema:position "3"^^<http://www.w3.org/2001/XMLSchema#integer>;
  schema:caption "Judgment of Paris Tasting";
  schema:contentUrl <B5deTaip/jop-tasting2.jpg>
].
```

This looks less pleasant,  but accurate in the jsonld files as well. 

```json
{
    "@id" : "#B5deTaip",
    "@type" : [ "schema:WebPage", "ucdlib:Story" ],
    "image" : [ "_:b18", "_:b19", "_:b0" ],
    "label" : "Story: Triptych",
    "license" : "http://rightsstatements.org/vocab/CNE/1.0/",
    "name" : "Triptych",
    "schema:position" : 9,
    "publisher" : "http://id.loc.gov/authorities/names/no2008108707"
  }, 
{
    "@id" : "_:b18",
    "@type" : "schema:ImageObject",
    "caption" : "Patricia Gallagher, Steven Spurrier, Odette Kahn",
    "contentUrl" : "B5deTaip/jop-tasting1.jpg",
    "schema:position" : 1
  }, {
    "@id" : "_:b19",
    "@type" : "schema:ImageObject",
    "caption" : "George Taber's Article",
    "contentUrl" : "B5deTaip/jop-article.jpg",
    "schema:position" : 2
  },
 {
    "@id" : "_:b0",
    "@type" : "schema:ImageObject",
    "caption" : "Judgment of Paris Tasting",
    "contentUrl" : "B5deTaip/jop-tasting2.jpg",
    "schema:position" : 3
  }
```

**Comment by qjhart** [comment]
For the JOP Headline, this also looks correct in the jsonld file, at least if we use the `schema:name` as the title, and the headline as the caption.

``` json
{
    "@id" : "#aQbPoT6L",
    "@type" : [ "ucdlib:Story", "schema:WebPage" ],
    "description" : "#Image Caption",
    "headline" : [ "And the Winner is...", "The Winning Wines" ],
    "label" : "Story: Image / Text",
    "license" : "http://rightsstatements.org/vocab/CNE/1.0/",
    "name" : "And the Winner is...",
    "schema:position" : 7,
    "publisher" : "http://id.loc.gov/authorities/names/no2008108707",
    "text" : [ "Although France was widely regarded as the top producer of fine Cabernet Sauvignon and Chardonnay, and California wines were little known, a California wine rated best in the red and white categories.", "George Taber, the sole journalist present at the tasting, memorialized the event for Time magazine. His article’s headline, “Judgment of Paris,” recalled the Greek myth in which Paris, son of a king, is asked to name the fairest among the goddesses Hera, Athena, and Aphrodite. Paris chooses Aphrodite, in exchange for her gift of Helen of Sparta, and his decision ignited the series of events that lead to the Trojan war." ],
    "thumbnail" : "aQbPoT6L/jop-wines.jpg"
  }
```

**Comment by qjhart** [comment]
@jrmerz The one issue with the caption was because the original card reads the invalid(?) Markdown line `#Image Caption` as a header while it needs to have a space `# Image Caption`.  I've fixed the card, and this is the only example of that issue in the story.  Unfortunately, it's hard to debug on the Trello side

**Comment by wrenaria** [comment]
@qjhart @jrmerz The caption is still showing in the header. Does that just mean the fixed trello data needs to be reimported or....?

**Comment by jrmerz** [comment]
Seems to be fixed with latest data import? @wrenaria
